project_dependencies: 
  - python
  - g++
  - java
package_manager: pip
package_manager_flags: -I
package_dependencies:
  - fake_dependency0
  - fake_dependency1
  - fake_dependency2
warning_severity: high
