name: Capstone :)

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run python script
        run: |
          import os
          rmfp = os.getenv('GITHUB_WORKSPACE') + '\\users.txt'
          rmfp.encode('unicode-escape')
          with open(rmfp, 'r') as f:
              for line in f:
                  name = line.rstrip() + ' learned about GitHub Actions!'
                  print(name)
        shell: python
